"""empty message

Revision ID: 48827d58a2e7
Revises: 
Create Date: 2017-04-27 12:11:00.160398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48827d58a2e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('manaCost', sa.String(), nullable=True),
    sa.Column('colors', sa.String(), nullable=True),
    sa.Column('types', sa.String(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('clans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('clan', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clan'], ['clans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('clans')
    op.drop_table('cards')
    # ### end Alembic commands ###
