version: '2'
services:
  web:
    build: .
    environment:
     - PYTHONPATH=./ magic/api/app
    ports:
     - "5000:5000"
    volumes:
     - .:/code
#  nginx:
#    image: "nginx:latest"
#      ports:
#      - "5000:80"
